dbt:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      threads: 1
      schema: star_schema
  target: dev
