version 1:

models:
  - name: dim_product
    description: The product dimensional table
    columns:
      - name: product_key
        description: The primary key of the table
        data_test:
          - unique
          - not_null
      - name: product_id
      - name: category
      - name: quantity
      - name: price
  - name: dim_customer
    description: The customer dimensional table
    columns:
      - name: customer_key
        description: The primary key of the table
        data_test:
          - unique
          - not_null
      - name: customer_id
      - name: gender
      - name: age
  - name: dim_date
    description: The data dimensional table
    columns: 
      - name: date_key
        description: The primay key of the table
        data_test:
          - unique
          - not_null
      - name: day_of_week
      - name: month
      - name: quarter
      - name: year
  - name: fact_sale
    description: The sale fact table
    columns:
      - name: sale_key
        description: The primary key of the table
        data_test:
          - unique
          - not_null
      - name: sale_id
      - name: customer_key
        description: Foreign ket to dim_customer
        test:
          - relationships:
            to: ref('dim_customer')
            field: customer_key
      - name: product_key
        description: Foreign key to dim_product
        test:
          - relationships:
            to: ref('dim_product')
            field: product_key
      - name: date_key
        description: Foreign key to dim_date
        test:
          - relationships:
            to: ref('dim_date')
            field: date_key
      - name: payment_method
      - name: shopping_mall
